version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    labels: []
  - package-ecosystem: swift
    directory: /
    schedule:
      interval: weekly
    labels: []
  - package-ecosystem: bundler
    directory: /
    schedule:
      interval: weekly
    labels: []
  - package-ecosystem: bazel
    directory: /
    schedule:
      interval: weekly
    labels: []
