version: 2
updates:
  - package-ecosystem: github-actions
    directories:
      - /
      - .github/actions/*
    schedule:
      interval: weekly
    labels: [dependencies]
  - package-ecosystem: swift
    directory: /
    schedule:
      interval: weekly
    labels: [dependencies]
  - package-ecosystem: bundler
    directory: /
    schedule:
      interval: weekly
    labels: [dependencies]
  - package-ecosystem: bazel
    directory: /
    schedule:
      interval: weekly
    labels: [dependencies]
