version: 2
updates:
  - &base
    package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    labels: [dependencies]
  - <<: *base
    package-ecosystem: swift
  - <<: *base
    package-ecosystem: bundler
  - <<: *base
    package-ecosystem: bazel
