language: generic
matrix:
  include:
    - script:
        - set -o pipefail && script/cibuild | xcpretty
        - pod lib lint SwiftLintFramework.podspec
      env: JOB=Xcode
      os: osx
      osx_image: xcode8.2
      before_install:
        - pod repo update
    - script: swift test
      env: JOB=SPM
      os: osx
      osx_image: xcode8.2
      before_script:
        - bundle install --jobs=3 --retry=3 --without documentation --path bundle
        - bundle exec danger
    - script: make docker_test
      env: JOB=Linux
      sudo: required
      services: docker
notifications:
  email: false
  slack: realmio:vPdpsG9NLDo2DNlbqtcMAQuE
after_success:
  - bash <(curl -s https://codecov.io/bash)
