language: generic
matrix:
  include:
    - script:
        - set -o pipefail && script/cibuild | xcpretty
        - pod lib lint
      os: osx
      osx_image: xcode8
      env: JOB=Xcode8
      before_install:
        - gem install cocoapods -v '1.1.1'
        - pod repo update
    - script: swift test
      os: osx
      osx_image: xcode8
      env: JOB=SPM
notifications:
  email: false
  slack: realmio:vPdpsG9NLDo2DNlbqtcMAQuE
after_success:
  - bash <(curl -s https://codecov.io/bash)
