language: generic
matrix:
  include:
    - script:
        - set -o pipefail && script/cibuild | xcpretty
        - pod lib lint SwiftLintFramework.podspec
      env: JOB=Xcode
      os: osx
      osx_image: xcode8.2
      before_install:
        - pod repo update --silent
    - script: swift test
      env: JOB=SPM
      os: osx
      osx_image: xcode8.2
    - script: make docker_test
      env: JOB=Linux3.1
      sudo: required
      services: docker
    - script: make docker_test_302
      env: JOB=Linux3.0.2
      sudo: required
      services: docker
notifications:
  email: false
  slack: realmio:vPdpsG9NLDo2DNlbqtcMAQuE
after_success:
  - bash <(curl -s https://codecov.io/bash)
