name: Copilot Setup Steps

on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/copilot-setup-steps.yml

jobs:
  # The job MUST be called `copilot-setup-steps` or it will not be picked up by Copilot.
  copilot-setup-steps:
    name: Perform
    runs-on: ubuntu-24.04
    # Swift containers don't work with Copilot
    # container: swift:6.1-noble
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Get Swift version
        id: swift_version
        run: echo "version=$(swift --version | grep '[5-9]\.[0-9]\+\.[0-9]' -o | head -1)" >> "$GITHUB_OUTPUT"
      - uses: actions/cache@v4
        with:
          key: ${{ runner.os }}-spm-${{ steps.swift_version.outputs.version }}-${{ hashFiles('Package.resolved', 'Package.swift') }}
          restore-keys: ${{ runner.os }}-spm-${{ steps.swift_version.outputs.version }}-
          path: .build
      - name: Build everything
        run: swift build --build-tests
