name: Plugins Sync

on:
  push:
    branches:
      - main
    paths:
      - 'Plugins/**'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  sync:
    name: Sync Plugins Folder
    runs-on: ubuntu-slim
    steps:
      - name: Checkout repository
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
        with:
          persist-credentials: false
      - name: Run file sync
        uses: BetaHuhn/repo-file-sync-action@8b92be3375cf1d1b0cd579af488a9255572e4619 # v1.21.1
        with:
          GH_PAT: ${{ secrets.SIMPLYDANNY_PLUGINS_SYNC }}
          IS_FINE_GRAINED: true
          CONFIG_PATH: .github/plugins-sync.yml
          SKIP_PR: true
          COMMIT_PREFIX: ðŸ”„ Workflow in 'realm/SwiftLint'
